FROM pytorch/pytorch:2.5.1-cuda12.4-cudnn9-devel

RUN apt-get update && apt-get install -y wget && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir nnunetv2 pybids antspyx antspynet tensorflow[and-cuda]

RUN mkdir -p /data/nnUNet_raw \
    && mkdir -p /data/nnUNet_preprocessed \
    && mkdir -p /data/nnUNet_results

ENV nnUNet_raw="/data/nnUNet_raw"\
    nnUNet_preprocessed="/data/nnUNet_preprocessed"\
    nnUNet_results="/data/nnUNet_results"

RUN wget -q https://huggingface.co/huggingbrain/AnatomicalVesselSeg/resolve/main/t1_model.zip \
    && nnUNetv2_install_pretrained_model_from_zip t1_model.zip \
    && rm t1_model.zip

RUN wget -q https://huggingface.co/huggingbrain/AnatomicalVesselSeg/resolve/main/t2_model.zip \
    && nnUNetv2_install_pretrained_model_from_zip t2_model.zip \
    && rm t2_model.zip

RUN wget -q https://huggingface.co/huggingbrain/AnatomicalVesselSeg/resolve/main/t1t2_model.zip \
    && nnUNetv2_install_pretrained_model_from_zip t1t2_model.zip \
    && rm t1t2_model.zip

COPY pyproject.toml README.md /src/anat2vessels/
COPY src/ /src/anat2vessels/src/
RUN pip install --no-cache-dir -e "/src/anat2vessels[docker]"

COPY docker/entrypoint.py /usr/local/bin/a2v-pipeline
RUN chmod +x /usr/local/bin/a2v-pipeline

WORKDIR /data

ENTRYPOINT ["a2v-pipeline"]
