name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.13", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade packaging tools
        run: python -m pip install --upgrade pip setuptools wheel

      - name: Install
        run: pip install ".[all]"

      - name: Test
        run: spin test